// config.bin - 10:53:04 07/12/15, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class aftp_units {
		version = 1;
		author = "AFTP Golas & Waffel";
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"A3_Characters_F_BLUFOR", "A3_Characters_F_Common", "A3_Characters_F_Heads", "A3_Modules_F", A3_UI_F, "A3_Structures_F_Items_Electronics"};
	};
};

class cfgMods {
	author = "AFTP Golas & Waffel";
};
